version: "3.8"

services:
  api:
    image: chatbot_rag:latest
    command: >
      bash -lc "uvicorn backend.app.main:app
                --host 0.0.0.0 --port ${API_PORT:-8000}"
    env_file: .env
    ports:
      - "${API_PORT:-8000}:8000"

  web:
    image: chatbot_rag:latest
    command: >
      bash -lc "streamlit run streamlit_app/app.py
                --server.port 8501
                --server.headless true"
    env_file: .env
    ports:
      - "8501:8501"
